My Capstone Project
================
Brittany Damazio
2023-12-18

**\#Introduction:**

Bellabeat is a high-tech manufacturer of health-focused products for
women. They are a successful small company but have the potential to
become a larger player in the global smart device market. Urška Sršen,
cofounder and Chief Creative Officer of Bellabeat, believes that
analyzing non-Bellabeat smart device fitness data could help unlock new
growth opportunities for the company.

This presentation details my analysis of datasets about smart device
usage data to gain insight into how consumers are using their
non-Bellabeat smart devices. This information will then be applied to
help guide marketing strategy for the company regarding Bellabeat
products.

**\#Phase 1: Ask**

Before we begin, it is important to identify the key stakeholders:

- Urška Sršen: Bellabeat’s co-founder and Chief Creative Officer
- Sando Mur: Mathematician and Bellabeat’s co-founder; key member of the
  Bellabeat executive team
- Bellabeat marketing analytics team: A team of data analysts
  responsible for collecting, analyzing, and reporting data that helps
  guide Bellabeat’s marketing strategy.

**\##Business Task**

Analyze Fitbit fitness data to gain insight into how consumers are using
their smart devices and the Fitbit app which can then be used in
discovering trends for Bellabeat usage to help guide marketing strategy.

**\##Questions that need to be answered are as follows:**

1.  What are some trends in Fitbit smart device usage?
2.  How could these trends apply to Bellabeat customers?
3.  How could these trends help influence Bellabeat marketing strategy?

**\#Phase 2: Prepare**

Sršen encouraged me to use public data that explores smart device users’
daily habits. She directed me to the following dataset:

Fitbit Fitness Tracker Data (CC0: Public Domain, dataset made available
through Mobius): This Kaggle dataset contains personal fitness tracker
from thirty Fitbit users. 30 eligible Fitbit users consented to the
submission of personal tracker data, including minute-level output for
physical activity, heart rate, and sleep monitoring. It includes
information about daily activity, steps, and heart rate that can be used
to explore users’ habits.

Before proceeding with the analysis, it was made clear that the dataset
might have some limitations, regardless, it is imperative to evaluate
the data and its sources. Constraints found are as follows:

- **Reliable?** This data uses a sample size of 30 Fitbit users which
  will not accurately represent the fitness tracker market in its
  entirety.
- **Original?** These datasets were generated by an Amazon Mechanical
  Turk survey (third-party provider) between 3/12/2016 and 5/12/2016.
- **Comprehensive?** This data is very comprehensive and there does not
  appear to be missing values.
- **Current?** This data was compiled in 2016, so it is likely that
  users’ habits for activity, exercising, and sleeping, along with diet
  and eating habits, may have changed.
- **Cited?** This data seems to be cited and in high use through the
  Kaggle website, though it is collected from a third-party survey and
  can be biased.

The dataset consists of 18 CSV files that are freely accessible on the
Kaggle website, containing relevant information on specific
health-related activities and/or parameters.

**\#Phase 3: Process**

In this phase, I will process the data to ensure that it is correct,
relevant, complete and without error. First, I want to ensure the data
does not contain null or missing values. To do this, I used RStudio. I
began by installing and reading all relevant packages:

``` r
install.packages("tidyverse", repos="http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/33/5bqvg78d67jf3dfv_xh4mjp40000gn/T//RtmpscLY6l/downloaded_packages

``` r
install.packages("lubridate", repos="http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/33/5bqvg78d67jf3dfv_xh4mjp40000gn/T//RtmpscLY6l/downloaded_packages

``` r
install.packages("dplyr", repos="http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/33/5bqvg78d67jf3dfv_xh4mjp40000gn/T//RtmpscLY6l/downloaded_packages

``` r
install.packages("ggplot2", repos="http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/33/5bqvg78d67jf3dfv_xh4mjp40000gn/T//RtmpscLY6l/downloaded_packages

``` r
install.packages("tidyr", repos="http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/33/5bqvg78d67jf3dfv_xh4mjp40000gn/T//RtmpscLY6l/downloaded_packages

``` r
install.packages("skimr", repos="http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/33/5bqvg78d67jf3dfv_xh4mjp40000gn/T//RtmpscLY6l/downloaded_packages

``` r
install.packages("janitor", repos="http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/33/5bqvg78d67jf3dfv_xh4mjp40000gn/T//RtmpscLY6l/downloaded_packages

``` r
install.packages("readr", repos="http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/33/5bqvg78d67jf3dfv_xh4mjp40000gn/T//RtmpscLY6l/downloaded_packages

``` r
install.packages("stringr", repos="http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/33/5bqvg78d67jf3dfv_xh4mjp40000gn/T//RtmpscLY6l/downloaded_packages

``` r
install.packages("sqldf", repos="http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/33/5bqvg78d67jf3dfv_xh4mjp40000gn/T//RtmpscLY6l/downloaded_packages

``` r
install.packages("plotrix", repos="http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/33/5bqvg78d67jf3dfv_xh4mjp40000gn/T//RtmpscLY6l/downloaded_packages

``` r
install.packages("here", repos="http://cran.us.r-project.org")
```

    ## 
    ## The downloaded binary packages are in
    ##  /var/folders/33/5bqvg78d67jf3dfv_xh4mjp40000gn/T//RtmpscLY6l/downloaded_packages

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.4.4     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.3     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(lubridate)
library(ggplot2)
library(dplyr)
library(skimr)
library(tidyr)
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'
    ## 
    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

``` r
library(stringr)
library(readr)
library(sqldf)
```

    ## Loading required package: gsubfn
    ## Loading required package: proto

    ## Warning in doTryCatch(return(expr), name, parentenv, handler): unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
    ##   dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 0x0006): Library not loaded: /opt/X11/lib/libSM.6.dylib
    ##   Referenced from: <FFA47D77-8F35-36FC-B0E5-38351B8D9512> /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/modules/R_X11.so
    ##   Reason: tried: '/opt/X11/lib/libSM.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/X11/lib/libSM.6.dylib' (no such file), '/opt/X11/lib/libSM.6.dylib' (no such file), '/Library/Frameworks/R.framework/Resources/lib/libSM.6.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-11.0.18+10/Contents/Home/lib/server/libSM.6.dylib' (no such file)

    ## tcltk DLL is linked to '/opt/X11/lib/libX11.6.dylib'
    ## Could not load tcltk.  Will use slower R code instead.
    ## Loading required package: RSQLite

``` r
library(plotrix)
library(here)
```

    ## here() starts at /Users/brittanydamazio/My-Capstone-Project

Then, I imported the data and stored it in relevant variables:

``` r
daily_activity <- read.csv("dailyActivity_merged.csv")
daily_steps <- read.csv("dailySteps_merged.csv")
daily_sleep <- read.csv("sleepDay_merged.csv")
weight_log <- read.csv("weightLogInfo_merged.csv")
calories <- read.csv("dailyCalories_merged.csv")
intensities <- read.csv("dailyIntensities_merged.csv")
```

To find the number of records and columns, any null or missing values,
and the data type of every column, I used the following command:

``` r
str(daily_activity)
```

    ## 'data.frame':    940 obs. of  15 variables:
    ##  $ Id                      : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ ActivityDate            : chr  "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
    ##  $ TotalSteps              : int  13162 10735 10460 9762 12669 9705 13019 15506 10544 9819 ...
    ##  $ TotalDistance           : num  8.5 6.97 6.74 6.28 8.16 ...
    ##  $ TrackerDistance         : num  8.5 6.97 6.74 6.28 8.16 ...
    ##  $ LoggedActivitiesDistance: num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ VeryActiveDistance      : num  1.88 1.57 2.44 2.14 2.71 ...
    ##  $ ModeratelyActiveDistance: num  0.55 0.69 0.4 1.26 0.41 ...
    ##  $ LightActiveDistance     : num  6.06 4.71 3.91 2.83 5.04 ...
    ##  $ SedentaryActiveDistance : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ VeryActiveMinutes       : int  25 21 30 29 36 38 42 50 28 19 ...
    ##  $ FairlyActiveMinutes     : int  13 19 11 34 10 20 16 31 12 8 ...
    ##  $ LightlyActiveMinutes    : int  328 217 181 209 221 164 233 264 205 211 ...
    ##  $ SedentaryMinutes        : int  728 776 1218 726 773 539 1149 775 818 838 ...
    ##  $ Calories                : int  1985 1797 1776 1745 1863 1728 1921 2035 1786 1775 ...

``` r
skim(daily_activity)
```

|                                                  |                |
|:-------------------------------------------------|:---------------|
| Name                                             | daily_activity |
| Number of rows                                   | 940            |
| Number of columns                                | 15             |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |                |
| Column type frequency:                           |                |
| character                                        | 1              |
| numeric                                          | 14             |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |                |
| Group variables                                  | None           |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| ActivityDate  |         0 |             1 |   8 |   9 |     0 |       31 |          0 |

**Variable type: numeric**

| skim_variable            | n_missing | complete_rate |         mean |           sd |         p0 |          p25 |          p50 |          p75 |         p100 | hist  |
|:-------------------------|----------:|--------------:|-------------:|-------------:|-----------:|-------------:|-------------:|-------------:|-------------:|:------|
| Id                       |         0 |             1 | 4.855407e+09 | 2.424805e+09 | 1503960366 | 2.320127e+09 | 4.445115e+09 | 6.962181e+09 | 8.877689e+09 | ▇▅▃▅▅ |
| TotalSteps               |         0 |             1 | 7.637910e+03 | 5.087150e+03 |          0 | 3.789750e+03 | 7.405500e+03 | 1.072700e+04 | 3.601900e+04 | ▇▇▁▁▁ |
| TotalDistance            |         0 |             1 | 5.490000e+00 | 3.920000e+00 |          0 | 2.620000e+00 | 5.240000e+00 | 7.710000e+00 | 2.803000e+01 | ▇▆▁▁▁ |
| TrackerDistance          |         0 |             1 | 5.480000e+00 | 3.910000e+00 |          0 | 2.620000e+00 | 5.240000e+00 | 7.710000e+00 | 2.803000e+01 | ▇▆▁▁▁ |
| LoggedActivitiesDistance |         0 |             1 | 1.100000e-01 | 6.200000e-01 |          0 | 0.000000e+00 | 0.000000e+00 | 0.000000e+00 | 4.940000e+00 | ▇▁▁▁▁ |
| VeryActiveDistance       |         0 |             1 | 1.500000e+00 | 2.660000e+00 |          0 | 0.000000e+00 | 2.100000e-01 | 2.050000e+00 | 2.192000e+01 | ▇▁▁▁▁ |
| ModeratelyActiveDistance |         0 |             1 | 5.700000e-01 | 8.800000e-01 |          0 | 0.000000e+00 | 2.400000e-01 | 8.000000e-01 | 6.480000e+00 | ▇▁▁▁▁ |
| LightActiveDistance      |         0 |             1 | 3.340000e+00 | 2.040000e+00 |          0 | 1.950000e+00 | 3.360000e+00 | 4.780000e+00 | 1.071000e+01 | ▆▇▆▁▁ |
| SedentaryActiveDistance  |         0 |             1 | 0.000000e+00 | 1.000000e-02 |          0 | 0.000000e+00 | 0.000000e+00 | 0.000000e+00 | 1.100000e-01 | ▇▁▁▁▁ |
| VeryActiveMinutes        |         0 |             1 | 2.116000e+01 | 3.284000e+01 |          0 | 0.000000e+00 | 4.000000e+00 | 3.200000e+01 | 2.100000e+02 | ▇▁▁▁▁ |
| FairlyActiveMinutes      |         0 |             1 | 1.356000e+01 | 1.999000e+01 |          0 | 0.000000e+00 | 6.000000e+00 | 1.900000e+01 | 1.430000e+02 | ▇▁▁▁▁ |
| LightlyActiveMinutes     |         0 |             1 | 1.928100e+02 | 1.091700e+02 |          0 | 1.270000e+02 | 1.990000e+02 | 2.640000e+02 | 5.180000e+02 | ▅▇▇▃▁ |
| SedentaryMinutes         |         0 |             1 | 9.912100e+02 | 3.012700e+02 |          0 | 7.297500e+02 | 1.057500e+03 | 1.229500e+03 | 1.440000e+03 | ▁▁▇▅▇ |
| Calories                 |         0 |             1 | 2.303610e+03 | 7.181700e+02 |          0 | 1.828500e+03 | 2.134000e+03 | 2.793250e+03 | 4.900000e+03 | ▁▆▇▃▁ |

``` r
head(daily_activity)
```

    ##           Id ActivityDate TotalSteps TotalDistance TrackerDistance
    ## 1 1503960366    4/12/2016      13162          8.50            8.50
    ## 2 1503960366    4/13/2016      10735          6.97            6.97
    ## 3 1503960366    4/14/2016      10460          6.74            6.74
    ## 4 1503960366    4/15/2016       9762          6.28            6.28
    ## 5 1503960366    4/16/2016      12669          8.16            8.16
    ## 6 1503960366    4/17/2016       9705          6.48            6.48
    ##   LoggedActivitiesDistance VeryActiveDistance ModeratelyActiveDistance
    ## 1                        0               1.88                     0.55
    ## 2                        0               1.57                     0.69
    ## 3                        0               2.44                     0.40
    ## 4                        0               2.14                     1.26
    ## 5                        0               2.71                     0.41
    ## 6                        0               3.19                     0.78
    ##   LightActiveDistance SedentaryActiveDistance VeryActiveMinutes
    ## 1                6.06                       0                25
    ## 2                4.71                       0                21
    ## 3                3.91                       0                30
    ## 4                2.83                       0                29
    ## 5                5.04                       0                36
    ## 6                2.51                       0                38
    ##   FairlyActiveMinutes LightlyActiveMinutes SedentaryMinutes Calories
    ## 1                  13                  328              728     1985
    ## 2                  19                  217              776     1797
    ## 3                  11                  181             1218     1776
    ## 4                  34                  209              726     1745
    ## 5                  10                  221              773     1863
    ## 6                  20                  164              539     1728

``` r
str(daily_sleep)
```

    ## 'data.frame':    413 obs. of  5 variables:
    ##  $ Id                : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ SleepDay          : chr  "4/12/2016 12:00:00 AM" "4/13/2016 12:00:00 AM" "4/15/2016 12:00:00 AM" "4/16/2016 12:00:00 AM" ...
    ##  $ TotalSleepRecords : int  1 2 1 2 1 1 1 1 1 1 ...
    ##  $ TotalMinutesAsleep: int  327 384 412 340 700 304 360 325 361 430 ...
    ##  $ TotalTimeInBed    : int  346 407 442 367 712 320 377 364 384 449 ...

``` r
skim(daily_sleep)
```

|                                                  |             |
|:-------------------------------------------------|:------------|
| Name                                             | daily_sleep |
| Number of rows                                   | 413         |
| Number of columns                                | 5           |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |             |
| Column type frequency:                           |             |
| character                                        | 1           |
| numeric                                          | 4           |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |             |
| Group variables                                  | None        |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| SleepDay      |         0 |             1 |  20 |  21 |     0 |       31 |          0 |

**Variable type: numeric**

| skim_variable      | n_missing | complete_rate |         mean |          sd |         p0 |        p25 |        p50 |        p75 |       p100 | hist  |
|:-------------------|----------:|--------------:|-------------:|------------:|-----------:|-----------:|-----------:|-----------:|-----------:|:------|
| Id                 |         0 |             1 | 5.000979e+09 | 2.06036e+09 | 1503960366 | 3977333714 | 4702921684 | 6962181067 | 8792009665 | ▆▆▇▅▃ |
| TotalSleepRecords  |         0 |             1 | 1.120000e+00 | 3.50000e-01 |          1 |          1 |          1 |          1 |          3 | ▇▁▁▁▁ |
| TotalMinutesAsleep |         0 |             1 | 4.194700e+02 | 1.18340e+02 |         58 |        361 |        433 |        490 |        796 | ▁▂▇▃▁ |
| TotalTimeInBed     |         0 |             1 | 4.586400e+02 | 1.27100e+02 |         61 |        403 |        463 |        526 |        961 | ▁▃▇▁▁ |

``` r
head(daily_sleep)
```

    ##           Id              SleepDay TotalSleepRecords TotalMinutesAsleep
    ## 1 1503960366 4/12/2016 12:00:00 AM                 1                327
    ## 2 1503960366 4/13/2016 12:00:00 AM                 2                384
    ## 3 1503960366 4/15/2016 12:00:00 AM                 1                412
    ## 4 1503960366 4/16/2016 12:00:00 AM                 2                340
    ## 5 1503960366 4/17/2016 12:00:00 AM                 1                700
    ## 6 1503960366 4/19/2016 12:00:00 AM                 1                304
    ##   TotalTimeInBed
    ## 1            346
    ## 2            407
    ## 3            442
    ## 4            367
    ## 5            712
    ## 6            320

``` r
str(weight_log)
```

    ## 'data.frame':    67 obs. of  8 variables:
    ##  $ Id            : num  1.50e+09 1.50e+09 1.93e+09 2.87e+09 2.87e+09 ...
    ##  $ Date          : chr  "5/2/2016 11:59:59 PM" "5/3/2016 11:59:59 PM" "4/13/2016 1:08:52 AM" "4/21/2016 11:59:59 PM" ...
    ##  $ WeightKg      : num  52.6 52.6 133.5 56.7 57.3 ...
    ##  $ WeightPounds  : num  116 116 294 125 126 ...
    ##  $ Fat           : int  22 NA NA NA NA 25 NA NA NA NA ...
    ##  $ BMI           : num  22.6 22.6 47.5 21.5 21.7 ...
    ##  $ IsManualReport: chr  "True" "True" "False" "True" ...
    ##  $ LogId         : num  1.46e+12 1.46e+12 1.46e+12 1.46e+12 1.46e+12 ...

``` r
skim(weight_log)
```

|                                                  |            |
|:-------------------------------------------------|:-----------|
| Name                                             | weight_log |
| Number of rows                                   | 67         |
| Number of columns                                | 8          |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |            |
| Column type frequency:                           |            |
| character                                        | 2          |
| numeric                                          | 6          |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |            |
| Group variables                                  | None       |

Data summary

**Variable type: character**

| skim_variable  | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:---------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| Date           |         0 |             1 |  19 |  21 |     0 |       56 |          0 |
| IsManualReport |         0 |             1 |   4 |   5 |     0 |        2 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate |         mean |           sd |           p0 |          p25 |          p50 |          p75 |         p100 | hist  |
|:--------------|----------:|--------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|-------------:|:------|
| Id            |         0 |          1.00 | 7.009282e+09 | 1.950322e+09 | 1.503960e+09 | 6.962181e+09 | 6.962181e+09 | 8.877689e+09 | 8.877689e+09 | ▁▁▂▇▆ |
| WeightKg      |         0 |          1.00 | 7.204000e+01 | 1.392000e+01 | 5.260000e+01 | 6.140000e+01 | 6.250000e+01 | 8.505000e+01 | 1.335000e+02 | ▇▃▃▁▁ |
| WeightPounds  |         0 |          1.00 | 1.588100e+02 | 3.070000e+01 | 1.159600e+02 | 1.353600e+02 | 1.377900e+02 | 1.875000e+02 | 2.943200e+02 | ▇▃▃▁▁ |
| Fat           |        65 |          0.03 | 2.350000e+01 | 2.120000e+00 | 2.200000e+01 | 2.275000e+01 | 2.350000e+01 | 2.425000e+01 | 2.500000e+01 | ▇▁▁▁▇ |
| BMI           |         0 |          1.00 | 2.519000e+01 | 3.070000e+00 | 2.145000e+01 | 2.396000e+01 | 2.439000e+01 | 2.556000e+01 | 4.754000e+01 | ▇▁▁▁▁ |
| LogId         |         0 |          1.00 | 1.461772e+12 | 7.829948e+08 | 1.460444e+12 | 1.461079e+12 | 1.461802e+12 | 1.462375e+12 | 1.463098e+12 | ▇▇▆▇▇ |

``` r
head(weight_log)
```

    ##           Id                  Date WeightKg WeightPounds Fat   BMI
    ## 1 1503960366  5/2/2016 11:59:59 PM     52.6     115.9631  22 22.65
    ## 2 1503960366  5/3/2016 11:59:59 PM     52.6     115.9631  NA 22.65
    ## 3 1927972279  4/13/2016 1:08:52 AM    133.5     294.3171  NA 47.54
    ## 4 2873212765 4/21/2016 11:59:59 PM     56.7     125.0021  NA 21.45
    ## 5 2873212765 5/12/2016 11:59:59 PM     57.3     126.3249  NA 21.69
    ## 6 4319703577 4/17/2016 11:59:59 PM     72.4     159.6147  25 27.45
    ##   IsManualReport        LogId
    ## 1           True 1.462234e+12
    ## 2           True 1.462320e+12
    ## 3          False 1.460510e+12
    ## 4           True 1.461283e+12
    ## 5           True 1.463098e+12
    ## 6           True 1.460938e+12

``` r
str(calories)
```

    ## 'data.frame':    940 obs. of  3 variables:
    ##  $ Id         : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ ActivityDay: chr  "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
    ##  $ Calories   : int  1985 1797 1776 1745 1863 1728 1921 2035 1786 1775 ...

``` r
skim(calories)
```

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | calories |
| Number of rows                                   | 940      |
| Number of columns                                | 3        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| character                                        | 1        |
| numeric                                          | 2        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| ActivityDay   |         0 |             1 |   8 |   9 |     0 |       31 |          0 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate |         mean |           sd |         p0 |          p25 |        p50 |          p75 |       p100 | hist  |
|:--------------|----------:|--------------:|-------------:|-------------:|-----------:|-------------:|-----------:|-------------:|-----------:|:------|
| Id            |         0 |             1 | 4.855407e+09 | 2.424805e+09 | 1503960366 | 2320127002.0 | 4445114986 | 6.962181e+09 | 8877689391 | ▇▅▃▅▅ |
| Calories      |         0 |             1 | 2.303610e+03 | 7.181700e+02 |          0 |       1828.5 |       2134 | 2.793250e+03 |       4900 | ▁▆▇▃▁ |

``` r
head(calories)
```

    ##           Id ActivityDay Calories
    ## 1 1503960366   4/12/2016     1985
    ## 2 1503960366   4/13/2016     1797
    ## 3 1503960366   4/14/2016     1776
    ## 4 1503960366   4/15/2016     1745
    ## 5 1503960366   4/16/2016     1863
    ## 6 1503960366   4/17/2016     1728

``` r
str(intensities)
```

    ## 'data.frame':    940 obs. of  10 variables:
    ##  $ Id                      : num  1.5e+09 1.5e+09 1.5e+09 1.5e+09 1.5e+09 ...
    ##  $ ActivityDay             : chr  "4/12/2016" "4/13/2016" "4/14/2016" "4/15/2016" ...
    ##  $ SedentaryMinutes        : int  728 776 1218 726 773 539 1149 775 818 838 ...
    ##  $ LightlyActiveMinutes    : int  328 217 181 209 221 164 233 264 205 211 ...
    ##  $ FairlyActiveMinutes     : int  13 19 11 34 10 20 16 31 12 8 ...
    ##  $ VeryActiveMinutes       : int  25 21 30 29 36 38 42 50 28 19 ...
    ##  $ SedentaryActiveDistance : num  0 0 0 0 0 0 0 0 0 0 ...
    ##  $ LightActiveDistance     : num  6.06 4.71 3.91 2.83 5.04 ...
    ##  $ ModeratelyActiveDistance: num  0.55 0.69 0.4 1.26 0.41 ...
    ##  $ VeryActiveDistance      : num  1.88 1.57 2.44 2.14 2.71 ...

``` r
skim(intensities)
```

|                                                  |             |
|:-------------------------------------------------|:------------|
| Name                                             | intensities |
| Number of rows                                   | 940         |
| Number of columns                                | 10          |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |             |
| Column type frequency:                           |             |
| character                                        | 1           |
| numeric                                          | 9           |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |             |
| Group variables                                  | None        |

Data summary

**Variable type: character**

| skim_variable | n_missing | complete_rate | min | max | empty | n_unique | whitespace |
|:--------------|----------:|--------------:|----:|----:|------:|---------:|-----------:|
| ActivityDay   |         0 |             1 |   8 |   9 |     0 |       31 |          0 |

**Variable type: numeric**

| skim_variable            | n_missing | complete_rate |         mean |           sd |         p0 |          p25 |          p50 |          p75 |         p100 | hist  |
|:-------------------------|----------:|--------------:|-------------:|-------------:|-----------:|-------------:|-------------:|-------------:|-------------:|:------|
| Id                       |         0 |             1 | 4.855407e+09 | 2.424805e+09 | 1503960366 | 2.320127e+09 | 4.445115e+09 | 6.962181e+09 | 8.877689e+09 | ▇▅▃▅▅ |
| SedentaryMinutes         |         0 |             1 | 9.912100e+02 | 3.012700e+02 |          0 | 7.297500e+02 | 1.057500e+03 | 1.229500e+03 | 1.440000e+03 | ▁▁▇▅▇ |
| LightlyActiveMinutes     |         0 |             1 | 1.928100e+02 | 1.091700e+02 |          0 | 1.270000e+02 | 1.990000e+02 | 2.640000e+02 | 5.180000e+02 | ▅▇▇▃▁ |
| FairlyActiveMinutes      |         0 |             1 | 1.356000e+01 | 1.999000e+01 |          0 | 0.000000e+00 | 6.000000e+00 | 1.900000e+01 | 1.430000e+02 | ▇▁▁▁▁ |
| VeryActiveMinutes        |         0 |             1 | 2.116000e+01 | 3.284000e+01 |          0 | 0.000000e+00 | 4.000000e+00 | 3.200000e+01 | 2.100000e+02 | ▇▁▁▁▁ |
| SedentaryActiveDistance  |         0 |             1 | 0.000000e+00 | 1.000000e-02 |          0 | 0.000000e+00 | 0.000000e+00 | 0.000000e+00 | 1.100000e-01 | ▇▁▁▁▁ |
| LightActiveDistance      |         0 |             1 | 3.340000e+00 | 2.040000e+00 |          0 | 1.950000e+00 | 3.360000e+00 | 4.780000e+00 | 1.071000e+01 | ▆▇▆▁▁ |
| ModeratelyActiveDistance |         0 |             1 | 5.700000e-01 | 8.800000e-01 |          0 | 0.000000e+00 | 2.400000e-01 | 8.000000e-01 | 6.480000e+00 | ▇▁▁▁▁ |
| VeryActiveDistance       |         0 |             1 | 1.500000e+00 | 2.660000e+00 |          0 | 0.000000e+00 | 2.100000e-01 | 2.050000e+00 | 2.192000e+01 | ▇▁▁▁▁ |

``` r
head(intensities)
```

    ##           Id ActivityDay SedentaryMinutes LightlyActiveMinutes
    ## 1 1503960366   4/12/2016              728                  328
    ## 2 1503960366   4/13/2016              776                  217
    ## 3 1503960366   4/14/2016             1218                  181
    ## 4 1503960366   4/15/2016              726                  209
    ## 5 1503960366   4/16/2016              773                  221
    ## 6 1503960366   4/17/2016              539                  164
    ##   FairlyActiveMinutes VeryActiveMinutes SedentaryActiveDistance
    ## 1                  13                25                       0
    ## 2                  19                21                       0
    ## 3                  11                30                       0
    ## 4                  34                29                       0
    ## 5                  10                36                       0
    ## 6                  20                38                       0
    ##   LightActiveDistance ModeratelyActiveDistance VeryActiveDistance
    ## 1                6.06                     0.55               1.88
    ## 2                4.71                     0.69               1.57
    ## 3                3.91                     0.40               2.44
    ## 4                2.83                     1.26               2.14
    ## 5                5.04                     0.41               2.71
    ## 6                2.51                     0.78               3.19

Using these commands, I found that there were 940 records in
daily_activity, 413 in daily_sleep, and 67 in weight_log. There are no
missing values in the dataset, however, there are many NA values in the
“Fat” variable in weight_log, so I removed this column using this
command:

``` r
weight_log2 <- subset(weight_log, select = -Fat)
```

I then changed the date format on daily_activity and daily_sleep to
reflect M/D/Y and to show the day of the week.

``` r
daily_activity$Date <- as.Date(daily_activity$ActivityDate, "%m/%d/%y")
daily_activity$month <- format(daily_activity$Date, "%B")
daily_activity$day_of_week <- format(daily_activity$Date, "%A")
```

``` r
daily_sleep$Date <- as.Date(daily_sleep$SleepDay, "%m/%d/%y")
daily_sleep$month <- format(daily_sleep$Date, "%B")
daily_sleep$day_of_week <- format(daily_sleep$Date, "%A")
```

The dataset claimed there were 30 users from the survey. I want to
verify this by counting the unique IDs using this command:

``` r
n_distinct(daily_activity$Id)
```

    ## [1] 33

``` r
n_distinct(daily_sleep$Id)
```

    ## [1] 24

``` r
n_distinct(daily_steps$Id)
```

    ## [1] 33

``` r
n_distinct(weight_log2$Id)
```

    ## [1] 8

``` r
n_distinct(calories$Id)
```

    ## [1] 33

``` r
n_distinct(intensities$Id)
```

    ## [1] 33

The daily_activity, daily_steps, calories, and intensities sets have 33
participants; The daily_sleep set has 24 participants, and the
weight_log2 set has only 8 participants, therefore, I will not be using
the weight_log2 set for my analysis as there just aren’t enough
participants for the results to be relevant.

**\#Phase 4: Analyze**

In order to find insights so that we can complete this project, we need
to summarize the data. I did this for each remaining dataset I’ve
chosen:

``` r
daily_activity %>%
  select(TotalSteps,
         TotalDistance,
         SedentaryMinutes,
         VeryActiveMinutes,
         Calories) %>%
  summary()
```

    ##    TotalSteps    TotalDistance    SedentaryMinutes VeryActiveMinutes
    ##  Min.   :    0   Min.   : 0.000   Min.   :   0.0   Min.   :  0.00   
    ##  1st Qu.: 3790   1st Qu.: 2.620   1st Qu.: 729.8   1st Qu.:  0.00   
    ##  Median : 7406   Median : 5.245   Median :1057.5   Median :  4.00   
    ##  Mean   : 7638   Mean   : 5.490   Mean   : 991.2   Mean   : 21.16   
    ##  3rd Qu.:10727   3rd Qu.: 7.713   3rd Qu.:1229.5   3rd Qu.: 32.00   
    ##  Max.   :36019   Max.   :28.030   Max.   :1440.0   Max.   :210.00   
    ##     Calories   
    ##  Min.   :   0  
    ##  1st Qu.:1828  
    ##  Median :2134  
    ##  Mean   :2304  
    ##  3rd Qu.:2793  
    ##  Max.   :4900

``` r
daily_sleep %>%
  select(TotalSleepRecords, 
         TotalMinutesAsleep, 
         TotalTimeInBed) %>%
  summary()
```

    ##  TotalSleepRecords TotalMinutesAsleep TotalTimeInBed 
    ##  Min.   :1.000     Min.   : 58.0      Min.   : 61.0  
    ##  1st Qu.:1.000     1st Qu.:361.0      1st Qu.:403.0  
    ##  Median :1.000     Median :433.0      Median :463.0  
    ##  Mean   :1.119     Mean   :419.5      Mean   :458.6  
    ##  3rd Qu.:1.000     3rd Qu.:490.0      3rd Qu.:526.0  
    ##  Max.   :3.000     Max.   :796.0      Max.   :961.0

``` r
weight_log2 %>%
  select(WeightPounds,
         BMI) %>%
  summary()
```

    ##   WeightPounds        BMI       
    ##  Min.   :116.0   Min.   :21.45  
    ##  1st Qu.:135.4   1st Qu.:23.96  
    ##  Median :137.8   Median :24.39  
    ##  Mean   :158.8   Mean   :25.19  
    ##  3rd Qu.:187.5   3rd Qu.:25.56  
    ##  Max.   :294.3   Max.   :47.54

From these summarizations, we can already see generalizations that can
be made based on these 30+/- participants. For example:

- The average number of steps participants walk per day is 7,406, less
  than the recommended 10,000 steps per day. Users on average report 991
  minutes of sedentary time, which is equivalent to about 16.5 hours.
  Users only average about 21 minutes of time that could be categorized
  as “very active” per day, burning an average of 2,304 calories per
  day.
- Participants averaged 419.5 minutes per sleep per day, or about 7
  hours. Participants also spent an average of 458.6 minutes in bed, a
  difference of 39.1 minutes, which could be indicative of the time
  spent falling asleep or getting out of bed in the morning. It is
  recommended to spend more than 90% of time in bed asleep, so this
  seems adequate.
- The average BMI of participants was 25.19 which is only slightly
  higher than the recommended healthy BMI range of 18-24.9.

**\#Phase 5: Share**

I will now create visualizations according to the analysis and project
goals.

I first wanted to determine the days that users had the most usage rates
on the FitBit Tracker app. To do so, I used this command:

``` r
daily_activity$day_of_week <- ordered(daily_activity$day_of_week, levels=c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
ggplot(data=daily_activity) + geom_bar(mapping = aes(x=day_of_week), fill="darkgreen") + labs(x="Day of the Week", y="Usage", title="Usage Rates for FitBit Tracker App")
```

![](My-Capstone-Project-Final_files/figure-gfm/unnamed-chunk-16-1.png)<!-- -->

According to the data, the frequency of usage of the FitBit tracker app
is highest on Sunday, Monday, and Tuesday. In my experience, Fridays and
Saturdays tend to be people’s busiest days of the week, with Sundays
being their days o relaxation. I believe this leads to people using
their apps more on Sunday, Monday, and Tuesday because they simply have
more time to do so. Further, people tend to think of Sundays as a fresh
start for the week, so it makes sense for Sundays to have the highest
app usage with each successive day slowly decreasing.

I then wanted to determine the amount of calories users burned and
compare that to the number of steps taken.

``` r
ggplot(data=daily_activity, aes(x=TotalSteps, y=Calories)) + 
  geom_point() + geom_smooth(color="darkgreen") + labs(x="Total Steps", y="Calories Burned", title="Calories Burned for Every Step Taken")
```

    ## `geom_smooth()` using method = 'loess' and formula = 'y ~ x'

![](My-Capstone-Project-Final_files/figure-gfm/unnamed-chunk-17-1.png)<!-- -->

This shows that there is a positive correlation between calories burned
and steps taken. This reflects what would be expected: the number of
calories burned increases with the quantity of steps taken.

I wanted to see the relationship between total steps and sedentary
steps.

``` r
ggplot(data=daily_activity, aes(x=TotalSteps, y=SedentaryMinutes)) +
  geom_point() + geom_smooth(method="loess", color="darkgreen") + labs(x="Total Steps", y="Sedentary Minutes", title="Total Steps vs. Sedentary Minutes")
```

    ## `geom_smooth()` using formula = 'y ~ x'

![](My-Capstone-Project-Final_files/figure-gfm/unnamed-chunk-18-1.png)<!-- -->

As users approach 10,000 steps per day, the relationship between
sedentary minutes and total steps is inverse. Once users pass 10,000 per
day, it’s more positive but does not show a significant change.

Then, I wanted to see the relationship between total minutes asleep and
total minutes in bed.

``` r
ggplot(data=daily_sleep, aes(x=TotalMinutesAsleep, y=TotalTimeInBed)) +
  geom_point()+ geom_smooth(method = lm, color="darkgreen") + labs(x="Total Minutes Asleep", y="Total Time in Bed", title=" Minutes Asleep vs. Minutes in Bed")
```

    ## `geom_smooth()` using formula = 'y ~ x'

![](My-Capstone-Project-Final_files/figure-gfm/unnamed-chunk-19-1.png)<!-- -->

According to this data, there is a strong positive correlation between
minutes spent in bed and minutes asleep, though there are some outliers
to the data at the top. This could be attributed to people spending more
tim in bed than asleep then the average person, though there is no
definitive reason why.

I now wanted to observe the relationship between minutes asleep and
minutes sedentary. To do so, I combined data from daily_activity and
daily_sleep.

``` r
merged_data <- merge(daily_sleep, daily_activity, by=c('Id', 'Date'))
head(merged_data)
```

    ##           Id       Date              SleepDay TotalSleepRecords
    ## 1 1503960366 2020-04-12 4/12/2016 12:00:00 AM                 1
    ## 2 1503960366 2020-04-13 4/13/2016 12:00:00 AM                 2
    ## 3 1503960366 2020-04-15 4/15/2016 12:00:00 AM                 1
    ## 4 1503960366 2020-04-16 4/16/2016 12:00:00 AM                 2
    ## 5 1503960366 2020-04-17 4/17/2016 12:00:00 AM                 1
    ## 6 1503960366 2020-04-19 4/19/2016 12:00:00 AM                 1
    ##   TotalMinutesAsleep TotalTimeInBed month.x day_of_week.x ActivityDate
    ## 1                327            346   April        Sunday    4/12/2016
    ## 2                384            407   April        Monday    4/13/2016
    ## 3                412            442   April     Wednesday    4/15/2016
    ## 4                340            367   April      Thursday    4/16/2016
    ## 5                700            712   April        Friday    4/17/2016
    ## 6                304            320   April        Sunday    4/19/2016
    ##   TotalSteps TotalDistance TrackerDistance LoggedActivitiesDistance
    ## 1      13162          8.50            8.50                        0
    ## 2      10735          6.97            6.97                        0
    ## 3       9762          6.28            6.28                        0
    ## 4      12669          8.16            8.16                        0
    ## 5       9705          6.48            6.48                        0
    ## 6      15506          9.88            9.88                        0
    ##   VeryActiveDistance ModeratelyActiveDistance LightActiveDistance
    ## 1               1.88                     0.55                6.06
    ## 2               1.57                     0.69                4.71
    ## 3               2.14                     1.26                2.83
    ## 4               2.71                     0.41                5.04
    ## 5               3.19                     0.78                2.51
    ## 6               3.53                     1.32                5.03
    ##   SedentaryActiveDistance VeryActiveMinutes FairlyActiveMinutes
    ## 1                       0                25                  13
    ## 2                       0                21                  19
    ## 3                       0                29                  34
    ## 4                       0                36                  10
    ## 5                       0                38                  20
    ## 6                       0                50                  31
    ##   LightlyActiveMinutes SedentaryMinutes Calories month.y day_of_week.y
    ## 1                  328              728     1985   April        Sunday
    ## 2                  217              776     1797   April        Monday
    ## 3                  209              726     1745   April     Wednesday
    ## 4                  221              773     1863   April      Thursday
    ## 5                  164              539     1728   April        Friday
    ## 6                  264              775     2035   April        Sunday

I then used this data to show the relationship graphically.

``` r
ggplot(data=merged_data, aes(x=TotalMinutesAsleep, y=SedentaryMinutes)) +
  geom_point(color="darkgreen") + geom_smooth(color="#b7410e") +
  labs(x="Minutes Asleep", y="Minutes Sedentary", title="Minutes Asleep vs. Minutes Sedentary")
```

    ## `geom_smooth()` using method = 'loess' and formula = 'y ~ x'

![](My-Capstone-Project-Final_files/figure-gfm/unnamed-chunk-21-1.png)<!-- -->

There is an overall negative correlation between sedentary minutes and
minutes asleep. This shows that users that sleep less tend to be more
sedentary, which could be due to overall low energy levels. This could
also be interpreted conversely in that less sedentary time during the
day could lead to more time asleep.

Then, I wanted to determine the percentage of activity by minutes. To do
so, I needed to calculate the sum of minutes from daily_activity.

``` r
activity_minutes <- sqldf("SELECT SUM(VeryActiveMinutes), SUM(FairlyActiveMinutes), SUM(LightlyActiveMinutes), SUM(SedentaryMinutes)
  FROM daily_activity")
head(activity_minutes)
```

    ##   SUM(VeryActiveMinutes) SUM(FairlyActiveMinutes) SUM(LightlyActiveMinutes)
    ## 1                  19895                    12751                    181244
    ##   SUM(SedentaryMinutes)
    ## 1                931738

I used this data to create a pie chart showing the percentage of
activity in minutes.

``` r
x <- c(19895,12751,181244,931738)
piepercent <- round(100*x / sum(x), 1)
colors = c("green", "orange", "blue", "yellow")

pie3D(x,labels = paste0(piepercent,"%"), col=colors,main = "Percentage of Activity in Minutes")
legend("bottomright", c("Very Active Minutes", "Fairly Active Minutes", "Lightly Active Minutes", "Sedentary Active Minutes"), cex=0.5, fill = colors)
```

![](My-Capstone-Project-Final_files/figure-gfm/unnamed-chunk-23-1.png)<!-- -->
The percentage of sedentary minutes is much higher than the others,
comprising 81.3%. The percentage of very active and fairly active
minutes is much lower than the others, comprising 1.7% and 1.3%
respectively.

**\#Phase 6: Act**

The goal of this analysis was to show how users were using the FitBit
Tracker app so that data can apply to the Bellabeat health tracker. This
information can then be used to determine the best marketing strategies
to apply to Bellabeat health products.

**\##What are some trends in Fitbit smart device usage?**

1.  Of all the information gathered, it was apparent that the FitBit app
    is most used to track steps and calories burned (940 observations).
    Less used the app to track sleep data (413 observations), and even
    less used the app to track weight information (67 observations).

2.  The frequency of usage of the FitBit tracker app is highest on
    Sunday, Monday, and Tuesday. In my experience, Fridays and Saturdays
    tend to be people’s busiest days of the week, with Sundays being
    their days o relaxation. I believe this leads to people using their
    apps more on Sunday, Monday, and Tuesday because they simply have
    more time to do so. Further, people tend to think of Sundays as a
    fresh start for the week, so it makes sense for Sundays to have the
    highest app usage with each successive day slowly decreasing.

3.  There is a positive correlation between calories burned and steps
    taken. Users also average 7,406 steps per day which is less than the
    recommended 10,000 steps per day.

4.  Users average 16.5 hours of sedentary time per day and 21 minutes of
    time that could be categorized as “very active.” Further, 81.3% of
    activity is categorized as “sedentary minutes.”

5.  The average users has 7 hours of sleep with an average of an
    additional 39 minutes spent in bed awake.

**\##How could these trends apply to Bellabeat customers?**

This data shows how non-Bellabeat customers are using their
non-Bellabeat smart devices to track their health information. Through
this analysis, we discovered the most frequently tracked stats and how
they apply to overall consumer health.

Bellabeat customers will likely be interested in similar information to
be provided through a Bellabeat smart decive app. These trends can be
used to integrate marketing strategies to help show that Bellabeat is
not only interested in user information, but genuinely cares for their
customers and betting their daily lifestyles.

**\##How could these trends help influence Bellabeat marketing
strategy?**

1.  Usage of FitBit app: It seems beneficial to focus marketing
    strategies more on tracking steps, calculating calories burned, and
    tracking sleep data than keeping weight logs.

2.  Decreased frequency of usage throughout week: A great marketing
    strategy for this could be to have some sort of rewards system in
    place to engage users in using their app throughout the week and
    encourage them to interact more each day.

3.  Calories burned vs. steps taken: I would recommend to give users the
    ability to set goals for both of these variables to beat each day.
    Further, it would be beneficial for there to be education for users
    to understand the importance of daily steps and calories burned to
    aid them in taking the initiative to better their numbers as well as
    ideas on how to do so.

4.  Sedentary and active minutes: A good marketing strategy for this
    could be to send reminders to users when they’ve been sedentary for
    too long. Another strategy could be to reward users when they
    average more than the recommended vigorous activity level of 21-42
    minutes per day.

5.  Time asleep vs. time in bed: A good marketing strategy here would be
    to provide the users the ability to set sleep goals and to help
    users understand the importance of healthy sleep habits to reduce
    the amount of time spent awake in bed.

**\#Conclusion**

It is important for Bellabeat to provide a smart device and app that is
unique and better than competitors. Why would a customer choose a device
like Fitbit over a device from Bellabeat? That is why I would recommend
not only allowing customers to set their own goals for certain stats
discussed above, but to also provide coaching and education to help
users understand the why behind some of their goals and how to achieve
them.
